"""empty message

Revision ID: e3357fb6154a
Revises: 
Create Date: 2020-01-02 14:59:06.382365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3357fb6154a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jumlah', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kategori', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rating', mysql.FLOAT(), nullable=False),
    sa.Column('deskripsi', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
